name: repository_gen
description: Getters and setters to save variables to and from Map
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build:
  source_gen:

dev_dependencies:
  build_test:
  build_runner:
  test: ^1.0.0
